@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/UNIVERSAL-AUTHORITY/project>
	deps:runtime-requirement         [ deps:on "Object::AUTHORITY"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "UNIVERSAL"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::More 0.61"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::Exception"^^deps:CpanId ].

